Repository dnd-side-project/dnd-11th-10-frontend, pull requests merged in 2024-08, with the labels that each got.

#2 docs: Issue, PR Template 추가
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: 📃 Docs

#8 feat: root 레이아웃 구성 및 Pretendard 폰트 적용
  public/fonts/PretendardVariable.woff2
  src/app/layout.tsx
  src/app/page.tsx
  tailwind.config.ts
  tsconfig.json
Labels: 🎨 Html&css

#11 feat: Header, Tab 컴포넌트 구현
  public/favicon.ico
  public/icons/search.svg
  public/images/logo.svg
  src/app/home/dictionary/page.tsx
  src/app/home/layout.tsx
  src/app/home/learning/page.tsx
  src/components/domain/home/Header/LoginButton.tsx
  src/components/domain/home/Header/index.tsx
  src/components/domain/home/Tabs/index.tsx
Labels: 🎨 Html&css

#9 feat: 사용할 color 상수화
  package-lock.json
  package.json
  postcss.config.mjs
  src/lib/core.ts
  src/styles/theme/colors.ts
  src/styles/theme/index.ts
  tailwind.config.ts
Labels: 🎨 Html&css

#16 feat: Tag 컴포넌트 구현 및 스토리 작성
  .storybook/preview.ts
  src/components/common/Tag/index.tsx
  src/components/shared/CategoryTag/CategoryTag.stories.tsx
  src/components/shared/CategoryTag/index.tsx
  src/components/shared/WordTag/WordTag.stories.tsx
  src/components/shared/WordTag/index.tsx
Labels: 🎨 Html&css

#18 Feat/#13
  public/icons/back.svg
  public/icons/cross.svg
  src/app/quiz/layout.tsx
  src/app/quiz/page.tsx
  src/app/quizstart/layout.tsx
  src/app/quizstart/page.tsx
  src/app/quiztypechoice/layout.tsx
  src/app/quiztypechoice/page.tsx
  src/components/domain/quiz/Header.tsx
  src/components/domain/quizstart/Header.tsx
  src/components/domain/quiztypechoice/Header.tsx
Labels: ✨ Feature, 🎨 Html&css

#23 feat: 용어 목록 페이지 UI 작업
  public/icons/arrow_up.svg
  public/icons/chat.svg
  public/icons/left_arrow.svg
  public/icons/search.svg
  public/icons/view.svg
  src/app/dictionary/page.tsx
  src/app/search/page.tsx
  src/components/domain/dictionary/OneWordItem/data.ts
  src/components/domain/dictionary/OneWordItem/index.tsx
  src/components/domain/dictionary/TabFilter/index.tsx
  src/components/domain/dictionary/WordsList/index.tsx
  src/components/shared/CategoryTag/index.tsx
  src/components/shared/SearchHeader/index.tsx
  src/components/shared/WordItem/index.tsx
  src/types/comment.ts
  src/types/word.ts
Labels: ✨ Feature, 🎨 Html&css

#26 design: Typography custom styles 정의, NotoSansKR 폰트 추가
  src/app/layout.tsx
  src/styles/theme/fontSize.ts
  src/styles/theme/index.ts
  tailwind.config.ts
Labels: 🎨 Html&css

#30 feat: BottomSheet 컴포넌트 구현
  package-lock.json
  package.json
  public/icons/check.svg
  public/icons/check_white.svg
  public/icons/google.svg
  src/app/layout.tsx
  src/components/common/BottomSheet/index.tsx
  src/components/common/Button/index.tsx
  src/components/shared/CheckboxBottomSheet/OneCheckbox.tsx
  src/components/shared/CheckboxBottomSheet/index.tsx
  src/components/shared/CommentBottomSheet/index.tsx
  src/components/shared/FilterBottomSheet/index.tsx
  src/components/shared/GoogleLoginButton/index.tsx
  src/components/shared/LoginBottomSheet/index.tsx
  src/components/shared/RadioBtnBottomSheet/OneRadioBtn.tsx
  src/components/shared/RadioBtnBottomSheet/index.tsx
  src/constants/bottomSheet.ts
  src/hooks/usetBottomSheetAction.tsx
  src/store/useUIStore.ts
Labels: ✨ Feature, 🎨 Html&css

#32 design: 홈(메인) 페이지 WordItem 컴포넌트 UI 변경 사항 반영, custom Typography 적용 수정
  src/app/dictionary/page.tsx
  src/components/common/HorizontalScrollArea/index.tsx
  src/components/common/Tag/index.tsx
  src/components/domain/dictionary/OneWordItem/index.tsx
  src/components/domain/dictionary/TabFilter/index.tsx
  src/components/domain/home/Tabs/index.tsx
  src/components/domain/home/dictionary/Bookmarks/index.tsx
  src/components/domain/home/dictionary/PopularCommentsList/index.tsx
  src/components/domain/home/dictionary/ViewAllWords/index.tsx
  src/components/domain/home/learning/CommunicationStats/CategoryChartItem.tsx
  src/components/domain/home/learning/CommunicationStats/TotalChart.tsx
  src/components/domain/home/learning/CommunicationStats/index.tsx
  src/components/domain/home/learning/TodayQuiz/index.tsx
  src/components/shared/CommentItem/index.tsx
  src/components/shared/SearchHeader/index.tsx
  src/components/shared/WordItem/index.tsx
Labels: 🎨 Html&css

#34 chore: Storybook 배포 테스트
  .github/workflows/storybook.yml
  src/components/common/BottomSheet/BottomSheet.stories.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/page.css
Labels: 🌏 Deploy

#38 design: 피드백 이후 디자인 수정 사항 반영
  public/icons/check_black.svg
  public/icons/check_white.svg
  src/components/common/Button/index.tsx
  src/components/common/HorizontalScrollArea/index.tsx
  src/components/common/Icons/RightArrow.tsx
  src/components/domain/home/dictionary/Bookmarks/index.tsx
  src/components/domain/home/dictionary/ViewAllWords/index.tsx
  src/components/domain/home/learning/TodayQuiz/index.tsx
  src/components/domain/home/learning/TodayWords/index.tsx
  src/components/shared/CheckboxBottomSheet/OneCheckbox.tsx
  src/styles/theme/fontSize.ts
  tailwind.config.ts
Labels: 🎨 Html&css

#46 feat: EmptyLayout 컴포넌트 UI 작업
  src/components/shared/EmptyLayout/index.tsx
  src/constants/emptyLayout.ts
Labels: ✨ Feature, 🎨 Html&css

#49 feat: HighlightText 공통 컴포넌트 구현, 스토리 작성
  src/components/common/HighlightText/HighlightText.stories.tsx
  src/components/common/HighlightText/index.tsx
  src/components/domain/wordDetail/WordInfo/index.tsx
Labels: ✨ Feature, 🎨 Html&css

#52 feat: axios instance 및 QueryProvider 생성
  package-lock.json
  package.json
  src/app/layout.tsx
  src/constants/env.ts
  src/lib/axios.ts
  src/provider/QueryProvider.tsx
  src/types/response.ts
Labels: ⚙ Setting, ✨ Feature, 📬 API

#53 design: 홈(메인) 페이지 디자인 수정 사항 반영
  public/images/home_quiz.svg
  public/images/logo.svg
  public/images/planet_purple.svg
  src/components/domain/home/Header/index.tsx
  src/components/domain/home/dictionary/Bookmarks/index.tsx
  src/components/domain/home/dictionary/ViewAllWords/index.tsx
  src/components/domain/home/learning/CommunicationStats/TotalChart.tsx
  src/components/domain/home/learning/TodayQuiz/index.tsx
Labels: 🎨 Html&css

#56 feat: 퀴즈 결과 카드 컴포넌트 추가 및 스토리북 작성
  public/icons/correct.svg
  public/icons/wrong.svg
  src/components/shared/QuizResultCard/QuizResultCard.stories.tsx
  src/components/shared/QuizResultCard/index.tsx
  src/types/quizresult.ts
Labels: 🎨 Html&css, 📃 Docs

#63 Feat/#58
  public/icons/job_group_01.svg
  public/icons/job_group_02.svg
  public/icons/job_group_03.svg
  src/components/common/SelectCard/index.tsx
  src/components/domain/profile/JobGroupCard/JobGroupCard.stories.tsx
  src/components/domain/profile/JobGroupCard/index.tsx
  src/types/profile.ts
Labels: ✨ Feature, 🎨 Html&css

#35 Feat/#21
  .gitignore
  public/icons/back.svg
  public/icons/front.svg
  public/icons/type_01.svg
  public/icons/type_02.svg
  public/icons/type_03.svg
  public/icons/type_04.svg
  public/images/quiz_start.svg
  public/images/speach_bubble_tail.svg
  src/app/not-found.tsx
  src/app/quiz/categorychoice/layout.tsx
  src/app/quiz/categorychoice/page.tsx
  src/app/quiz/page.tsx
  src/app/quiz/problem/[category]/[index]/layout.tsx
  src/app/quiz/problem/[category]/[index]/page.tsx
  src/app/quiz/start/layout.tsx
  src/app/quiz/start/page.tsx
  src/app/quizstart/page.tsx
  src/app/quiztypechoice/layout.tsx
  src/app/quiztypechoice/page.tsx
  src/components/domain/quiz/Header.tsx
  src/components/domain/quiz/data.ts
  src/components/domain/quiz/problem/header/Header.tsx
  src/components/domain/quiz/problem/header/index.ts
  src/components/domain/quiz/problem/index.ts
  src/components/domain/quiz/start/header/Header.tsx
  src/components/domain/quiz/start/header/index.ts
  src/components/domain/quiz/start/index.ts
  src/components/domain/quiz/typechoice/categoryCard/CategoryCard.tsx
  src/components/domain/quiz/typechoice/categoryCard/data.ts
  src/components/domain/quiz/typechoice/categoryCard/index.ts
  src/components/domain/quiz/typechoice/header/Header.tsx
  src/components/domain/quiz/typechoice/header/index.ts
  src/components/domain/quiz/typechoice/index.ts
  src/components/domain/quizstart/Header.tsx
  src/components/domain/quiztypechoice/Header.tsx
  src/lib/store.ts
  src/styles/theme/colors.ts
  src/types/quiz.ts
  src/types/quizresult.ts
Labels: ✨ Feature, 🎨 Html&css
