Repository dnd-side-project/dnd-11th-10-frontend, pull requests merged in 2024-09, with the labels that each got.

#67 design: 디자인 변경 사항 적용
  public/images/comment.svg
  public/images/contact.svg
  public/images/like_comment.svg
  public/images/planet_purple.svg
  public/images/star.svg
  public/images/star_ring.svg
  public/images/telescope.svg
  src/app/bookmarks/page.tsx
  src/app/dictionary/page.tsx
  src/app/globals.css
  src/app/words/[slug]/page.tsx
  src/components/common/Button/index.tsx
  src/components/domain/home/dictionary/Bookmarks/index.tsx
  src/components/domain/home/dictionary/PopularCommentsList/PopularCommentItem.tsx
  src/components/domain/home/dictionary/RecentlyAddedWords/index.tsx
  src/components/domain/home/dictionary/ViewAllWords/index.tsx
  src/components/domain/home/learning/CommunicationStats/index.tsx
  src/components/domain/home/learning/TodayQuiz/index.tsx
  src/components/domain/home/learning/TodayWords/index.tsx
  src/components/domain/wordDetail/CommentTextarea/index.tsx
  src/components/domain/wordDetail/ContactButton/index.tsx
  src/components/shared/Header/Header.stories.tsx
  src/components/shared/WordCard/index.tsx
  src/constants/bottomSheet.ts
  src/constants/emptyLayout.ts
  tailwind.config.ts
Labels: 🎨 Html&css

#92 feat: 사전 용어 목록 조회 구현
  src/api/words/index.ts
  src/app/dictionary/page.tsx
  src/components/common/SortButton/index.tsx
  src/components/domain/dictionary/WordsList/index.tsx
  src/components/shared/FilterBottomSheet/index.tsx
  src/components/shared/TopButton/index.tsx
  src/components/shared/WordListItem/data.ts
  src/components/shared/WordListItem/index.tsx
  src/hooks/useCreateQueryString.tsx
  src/hooks/word/useGetAllWords.ts
  src/provider/QueryProvider.tsx
  src/types/response.ts
  src/types/word.ts
Labels: ✨ Feature, 📬 API

#93 design: 퀴즈 부분 변경된 디자인 & 공통 컴포넌트 적용
  src/app/quiz/categorychoice/page.tsx
  src/app/quiz/problem/[category]/[index]/page.tsx
  src/app/quiz/start/page.tsx
  src/components/domain/quiz/problem/header/Header.tsx
  src/components/domain/quiz/typechoice/categoryCard/CategoryCard.tsx
Labels: 🎨 Html&css

#94 feat: (관리자) 용어 등록 페이지 UI 작업 및 admin 페이지 레이아웃 변경
  src/api/admin/words/index.ts
  src/app/admin/layout.tsx
  src/app/admin/page.tsx
  src/app/admin/words/[slug]/page.tsx
  src/app/admin/words/add/page.tsx
  src/app/layout.tsx
  src/components/common/Button/index.tsx
  src/components/common/Input/index.tsx
  src/components/domain/admin/WordDetail/index.tsx
  src/hooks/admin/useGetDetailWord.ts
  src/middleware.ts
  src/types/word.ts
Labels: ✨ Feature, 🎨 Html&css

#95 feat: Snackbar 컴포넌트 구현 및 스토리 작성
  src/components/domain/home/dictionary/PopularCommentsList/index.tsx
  src/components/domain/wordDetail/CommentsList/index.tsx
  src/components/shared/CheckboxBottomSheet/index.tsx
  src/components/shared/Snackbar/Snackbar.stories.tsx
  src/components/shared/Snackbar/index.tsx
  src/constants/bottomSheet.ts
  src/constants/snackbar.ts
  src/hooks/useSnackbarAction.tsx
  src/hooks/usetBottomSheetAction.tsx
  src/store/useUIStore.ts
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Html&css

#82 feat: 퀴즈 나가기 전 확인 모달 추가 및 스토리북 작성
  package-lock.json
  package.json
  src/components/common/Modal/Modal.stories.tsx
  src/components/common/Modal/index.tsx
  src/components/shared/QuizProblemStopModal/index.tsx
Labels: 🎨 Html&css

#106 feat: 용어 상세 정보 페이지 조회 기능 구현
  src/api/words/index.ts
  src/app/words/[slug]/page.tsx
  src/components/domain/wordDetail/Header/index.tsx
  src/components/domain/wordDetail/WordInfo/index.tsx
  src/hooks/word/useGetWordDetail.ts
  src/types/word.ts
Labels: ✨ Feature, 📬 API

#107 fix: admin 용어 등록 폼 resource(출처) 필드 추가
  src/app/admin/words/add/page.tsx
  src/types/word.ts
Labels: 🎨 Html&css

#108 feat: token 관리 로직 추가
  src/app/google/callback/loading/page.tsx
  src/lib/axios.ts
  src/store/useAuthStore.ts
Labels: ✨ Feature, 📬 API

#109 feat: 사전 탭 페이지 기능 구현
  src/api/comment/index.tsx
  src/api/words/index.ts
  src/app/home/dictionary/page.tsx
  src/components/common/HorizontalScrollArea/index.tsx
  src/components/domain/home/dictionary/PopularCommentsList/PopularCommentItem.tsx
  src/components/domain/home/dictionary/PopularCommentsList/index.tsx
  src/components/domain/home/dictionary/RecentlyAddedWords/index.tsx
  src/components/shared/CategoryTag/index.tsx
  src/constants/env.ts
  src/hooks/comment/useGetPopularComments.ts
  src/hooks/word/useGetRecentWords.ts
  src/types/comment.ts
Labels: ✨ Feature, 📬 API

#116 feat: 용어 상세 페이지 댓글 목록 조회 및 댓글 새로고침 기능 구현
  src/api/comment/index.tsx
  src/app/words/[slug]/page.tsx
  src/components/domain/wordDetail/CommentTextarea/index.tsx
  src/components/domain/wordDetail/CommentsList/index.tsx
  src/hooks/comment/useGetComments.ts
Labels: ✨ Feature, 📬 API

#117 feat: 전체 용어 개수 조회 api 연동
  src/api/admin/words/index.ts
  src/components/domain/home/dictionary/ViewAllWords/index.tsx
Labels: 📬 API

#120 feat: 프로필수정 페이지 레이아웃 추가 및 상태관리
  public/icons/goto_01.svg
  public/icons/goto_02.svg
  public/icons/goto_03.svg
  public/images/profile.svg
  src/app/mypage/layout.tsx
  src/app/mypage/page.tsx
  src/components/domain/mypage/GotoCard/GotoCard.tsx
  src/components/domain/mypage/GotoCard/index.ts
  src/components/domain/mypage/QuizStatus/QuizStatus.tsx
  src/components/domain/mypage/QuizStatus/index.ts
  src/components/domain/mypage/index.ts
  src/components/domain/mypage/information/Information.tsx
  src/components/domain/mypage/information/index.ts
  src/constants/account.ts
  src/constants/gotoCardData.ts
Labels: ✨ Feature, 🎨 Html&css
